### ISSUE TITLE
linter: Credentials Scanning Roadmap

### ISSUE THREAD

**Issue by DonIsaac** [oxc-project/backlog#116]
# Roadmap
- [x] add `oxc-security` plugin
- [x] https://github.com/oxc-project/oxc/pull/5906
- [ ] Allow enabling and disabling built-in secret scanners via config
- [ ] Allow user-provided custom API key patterns (https://github.com/oxc-project/oxc/pull/5938)
- [ ] Use const string eval to interpolate template strings

# Built-In Secret Scanners
- [x] AWS access keys (https://github.com/oxc-project/oxc/pull/5906)
- [ ] OpenAI API keys
- [ ] Slack, Discord, and Teams webhooks
- [ ] Private RSA keys
- [ ] Hard-coded `Authorization: Bearer <token>`
