### ISSUE TITLE
editor: Q4 Editor Goals

### ISSUE THREAD

**Issue by DonIsaac** [oxc-project/backlog#131]
## Goals
- [x] oxc-project/oxc#7308
- [x] oxc-project/oxc#7455
- [ ] oxc-project/oxc#7456

## Side Goals & Bugs
- [x] oxc-project/oxc#7451

**Comment by Boshen** [comment]
All issues are tracked in oxc.
